### ISSUE TITLE
Eorzea Database Identifiers

### ISSUE THREAD

**Issue by Dealman** [xivapi/SaintCoinach#144]
Is there a way to retrieve the identifier that the official Eorzea Database uses for items/recipes? For example for blacksmithing recipe  [Iron Ingot](https://na.finalfantasyxiv.com/lodestone/playguide/db/recipe/7f0f9bc3256/) it is `7f0f9bc3256`.

Not sure if this identifier is stored in the GameData or if it's generated specifically for their server-sided database. Could be useful if scraping the official database would be necessary to grab data such as NPCs selling the item or where it can be gathered.

**Comment by goaaats** [comment]
Sorry, we're not aware of any way to guess those IDs.
