### ISSUE TITLE
ui and uihd fail for a large number of image files.  Error message: Non-negative number required.  Parameter name: Value

### ISSUE THREAD

**Issue by xurkane** [xivapi/SaintCoinach#161]
This appears to happen for many new images for patch 6.5, but I am not certain if there are any older images that do this as well.

I did a reinstall of the game files using the official launcher, as well as an integrity check via XL, to ensure there was no issue with game files.

Example shown below, but I can provide a full list of all images that error if needed.

```
> uihd 024099
024099: Non-negative number required.
Parameter name: value
0 images processed

```

**Comment by Supamiu** [comment]
Hi, thanks for reporting

Many people are on it at the moment 🙂
