### ISSUE TITLE
Unhandled exception trying to run SaintCoinach.Cmd.exe

### ISSUE THREAD

**Issue by jtabox** [xivapi/SaintCoinach#171]
Hey, as the title says, I'm getting the following exception when I try to run the latest version of SaintCoinach CLI [51fd6b6](https://github.com/xivapi/SaintCoinach/releases/tag/51fd6b6):

```
Unhandled exception. System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section system.data (D:\ffadds\gamedata\progs\SaintCoinachGodbert\new\SaintCoinach.Cmd.dll.config line 20)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
...
   at SaintCoinach.Cmd.Program.Main(String[] args) in D:\a\SaintCoinach\SaintCoinach\SaintCoinach.Cmd\Program.cs:line 20
   ```

This happens only with the latest version ([51fd6b6](https://github.com/xivapi/SaintCoinach/releases/tag/51fd6b6)). I can run the previous one ([cc3954a](https://github.com/xivapi/SaintCoinach/releases/tag/cc3954a)) without any issues. Also, Godbert runs fine both in the current and the previous version.
I'm pretty much ignorant of C# in general, so I'm not sure what I can do. The file `SaintCoinach.Cmd.dll.config` that the error message mentions doesn't exist in the new version, but there's an identical file in the new version named `SaintCoinach.Cmd.exe.config`. The only difference I can see between those two, is that this segment is missing from the new .config file:
```
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1"/>
  </startup>
```
Also line 20 of `SaintCoinach.Cmd.dll.config` that's mentioned in the exception is: `<system.data>`.
My installed .NET Framework versions are 4.7.2 and 4.8.1 (and .NET SDK's versions 8.0.1 and 7.0.4), and I'm running Windows 11 Pro, in case it matters. I also see there's a bunch of new/changed files and a new folder in the new version, so I assume it's somehow related?

Is there something I can do to get the new version running?

**Comment by WanQiyang** [comment]
You can remove the lines between `<system.data>` and `</system.data>` (line 20-26) in the `SaintCoinach.Cmd.dll.config`. It works for me.
