### ISSUE TITLE
Godbert: Crash when exporting certain territories

### ISSUE THREAD

**Issue by gm-xanther** [xivapi/SaintCoinach#18]
When attempting to export the areas a2f2 or e0109 (Azys Lla) an error is presented and the export is unable to finish.
![azyserror](https://user-images.githubusercontent.com/25374987/127308502-657017c0-949b-47a0-bde5-ab023dfc5784.png)

An additional question, so as not to clutter the board: is there any way to export Demi-Humans, especially with their animations? The Monsters come out great! 

Thank you for all you do on this project, it's wonderful and hugely appreciated!

**Comment by IcarusTwine** [comment]
The whole 3d section of SaintC is something that has long been abandoned unfortunately, it became too much of a hassle to deal with to keep up to date.

**Comment by gm-xanther** [comment]
Well that's depressing, but thanks for the info.
