### ISSUE TITLE
failed to load model

### ISSUE THREAD

**Issue by SayuriMio** [xivapi/SaintCoinach#187]
![image_2024-06-26_165244241](https://github.com/xivapi/SaintCoinach/assets/173959334/a8339471-d676-44dd-a038-459b7592c3b4)

im not sure why but i keep getting this error when trying to view something in the 3d viewer in the equipment tab.

**Comment by Soveia** [comment]
The 3D viewing tool in Godbert is ancient, hasn't been worked on in many years and is almost certainly incompatible with the graphics update. Other tools like Textools have long since superseded it.
