### ISSUE TITLE
Bard Instrument Sound Files

### ISSUE THREAD

**Issue by majorcyto** [xivapi/SaintCoinach#19]
Hi,

I am currently trying to track down the instrument sound files that bards use for instrument playing, do you guys have these mapped or is the included command line tool able to export these? I have been searching through files manually for a while but have not found them yet.

I know this is not an issue per-say but you guys don't have discussions enabled and I don't see a Discord link anywhere.

**Comment by goaaats** [comment]
https://github.com/goaaats/MSBTool

I don't think we will support this format in SC, but you can use that tool to export/import midi.

**Comment by majorcyto** [comment]
While that is useful in a different way, I am trying to find the actual audio files themselves that produce the note sounds inside the client. I want to turn them into a soundfont so we can get an accurate preview of what it would sound like in-game.. outside of the game.

I was hoping someone here has come across them before and can point me in their direction. 🥺

**Comment by IcarusTwine** [comment]
> While that is useful in a different way, I am trying to find the actual audio files themselves that produce the note sounds inside the client. I want to turn them into a soundfont so we can get an accurate preview of what it would sound like in-game.. outside of the game.
> 
> I was hoping someone here has come across them before in the client directories and can point me in their direction. 🥺

sound/instruments/001grandpiano.scd
sound/instruments/026steelguitar.scd
ect

**Comment by majorcyto** [comment]
@IcarusTwine thank you! But where is that at, As in which game sqpack. Or can the command line tool here export it? Sorry but I have not done much data mining on the FFXIV client myself so I don't have a lot of experience with it. I just need to get these files into a .wav or .mp3 format so I can make a preview tool outside of the game.

**Comment by IcarusTwine** [comment]
> @IcarusTwine thank you! But where is that at, As in which game sqpack. Or can the command line tool here export it? Sorry but I have not done much data mining on the FFXIV client myself so I don't have a lot of experience with it. I just need to get these files into a .wav or .mp3 format so I can make a preview tool outside of the game.

0700000 is sound effects. you can extract using saint C any file if you know the path.
to be honest you will probably have an easier time just to record them yourself lol.

**Comment by majorcyto** [comment]
Just leaving a note here for anyone else that happens upon it, I was able to get all of the sound files and soundfonts I needed via MoogleTroupe on Discord.
