### ISSUE TITLE
Create object of "File" from file on hard drive, not from "SqPack". 

### ISSUE THREAD

**Issue by SanyaBane** [xivapi/SaintCoinach#2]
Is it possible to create a "File" not from a SqPack, but from external file on hard drive?

I want to edit skeleton of character (change length between some bones - for example "neck" and "head") and then export animation as FBX. 
In order to achieve it, I think the only thing I need is object of "File" class, which is **created from edited by me file** (which is stored somewhere on a hard drive), instead of original skeleton inside game files.
For example:
**D:\\skl_c0101b0001_edited.sklb**

Does anybody know how it might be achieved?

**Comment by IcarusTwine** [comment]
This cannot / will not be done with SaintCoinach sorry, you have the wrong project.

**Comment by SanyaBane** [comment]
I didn't get what exactly you mean by

> you have the wrong project

but thanks for response anyway!
