### ISSUE TITLE
Not existing Path

### ISSUE THREAD

**Issue by qludy** [xivapi/SaintCoinach#25]
Hello,

I have an error using StCoinach : 
System.IO.DirectoryNotFoundException : 'Tentative d'accès à un chemin d'accès ne se trouvant pas sur le disque.' (Access attemp to a path that isn't on the disk)
The path : {C:\Users\Admin\AppData\Local\Temp\tmpA6E9.tmp\2021.07.15.0000.0000}

Is there a way to avoid that ? The GameDirectory is good and used to work a year ago.

Thank you in advance,

Jokoast.

The full stacktrace :
```Exception non gérée : System.IO.DirectoryNotFoundException: Tentative d'accès à un chemin d'accès ne se trouvant pas sur le disque.
   à SaintCoinach.IO.PackCollection..ctor(DirectoryInfo dataDirectory) dans D:\Coding\C#\SaintCoinach-master\SaintCoinach\IO\PackCollection.cs:ligne 30
   à SaintCoinach.IO.PackCollection..ctor(String dataDirectory) dans D:\Coding\C#\SaintCoinach-master\SaintCoinach\IO\PackCollection.cs:ligne 24
   à SaintCoinach.ARealmReversed.Update(Boolean detectDataChanges, IProgress`1 progress) dans D:\Coding\C#\SaintCoinach-master\SaintCoinach\ARealmReversed.cs:ligne 366
   à GetItems.Program.Main() dans D:\Coding\C#\SaintCoinach-master\GetItems\Program.cs:ligne 27

**Comment by Nerothos** [comment]
Did you put the path between quotes?

**Comment by Hezkezl** [comment]
Been almost 4 months since this issue was opened and the author hasn't replied to Nerothos's suggestion. Probably should be closed since it's seemingly been abandoned.

**Comment by rockhyrax** [comment]
I occasionally hit this error when running `ARealmReversed::Update`. I haven't dug into it much, but it appears that `ExtractPacks` doesn't find anything that matches the `previousVersion` prefix, so it never generates the directory structure for that version that `PackCollection` expects, and thus it hits the exception.
FWIW, deleting the `SaintCoinach.History` file and re-running seems to work around the issue.
