### ISSUE TITLE
Dead Link: SaintCoinach.History.zip

### ISSUE THREAD

**Issue by gbtgbtgbta** [xivapi/SaintCoinach#32]
Link on main page for https://github.com/xivapi/SaintCoinach/blob/master/SaintCoinach/SaintCoinach.History.zip is dead.

**Comment by Hezkezl** [comment]
It's meant to be a dead link. That file isn't provided, it's created by the .exe when you run it. It contains backups of the dat files, so distributing that would be copyright infringement.
